// lib/voices/bland-voices.ts
// Official Callengo Voice Catalog — Curated & audited March 2026
// 51 voices | 2 languages | 5 accents | English (American, British, Australian) + Spanish (European, Latin American)

import { BlandVoice } from './types';

export const BLAND_VOICES: BlandVoice[] = [
  // ── American English ──────────────────────────────────────────────
  {"id":"ff2c405b-3dba-41e0-9261-bc8ee3f91f46","name":"David","description":"Young, confident and energetic African-American male voice. Engaging and dynamic.","public":true,"ratings":0,"tags":["american","male","english","young","confident","energetic"],"user_id":null,"total_ratings":5,"average_rating":5},
  {"id":"78982ab1-6a3f-4320-97f5-73bdb853f73d","name":"Freddie","description":"Energetic, motivated and friendly young female. Charismatic and upbeat.","public":true,"ratings":0,"tags":["american","female","english","young","energetic","friendly","charismatic"],"user_id":null,"total_ratings":6,"average_rating":5},
  {"id":"b93a4030-8391-4c54-a35a-7983a3e7a16a","name":"Keelan","description":"Mature, professional African-American female. Warm and calming presence.","public":true,"ratings":0,"tags":["american","female","english","mature","professional","warm"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"db93116d-b24b-48a6-863c-84afed20cac4","name":"Maeve","description":"Mature, warm and motherly female voice. Professional with a caring tone.","public":true,"ratings":0,"tags":["american","female","english","mature","warm","motherly","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"bdcad772-f6a8-4b63-95ca-3bae0d92f87e","name":"Chris","description":"Young male with a deep voice. Fast-paced, professional and direct.","public":true,"ratings":0,"tags":["american","male","english","young","deep","fast","professional","direct"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"78c8543e-e5fe-448e-8292-20a7b8c45247","name":"Harper","description":"Energetic, positive and friendly adult female. Fast-paced and upbeat.","public":true,"ratings":0,"tags":["american","female","english","adult","energetic","positive","friendly","fast"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"5aff7b0c-92d7-4ce6-a502-39d33a401808","name":"Isabelle","description":"Young, cheerful and soft female voice. Refined, professional and pleasant.","public":true,"ratings":0,"tags":["american","female","english","young","cheerful","soft","refined","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"6277266e-01eb-44c6-b965-438566ef7076","name":"Alexandra","description":"Young, fast-paced and resolute female. Quick and decisive.","public":true,"ratings":0,"tags":["american","female","english","young","fast","resolute"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"e54a409c-daa9-4ee6-a954-2d81dec3476b","name":"Alena","description":"Adult female with a flat, serious tone. Calm and warm undertone.","public":true,"ratings":0,"tags":["american","female","english","adult","serious","calm","warm"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"35571497-da9d-414b-b1b9-b1e68ef41f97","name":"Paige","description":"Young, warm and soft female. Fast-paced but gentle delivery.","public":true,"ratings":0,"tags":["american","female","english","young","warm","soft","fast"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"070f5aba-ce9d-4a15-ab68-5330695ed1d6","name":"Jane","description":"Young, slow and soft-spoken female. Gentle and delicate voice.","public":true,"ratings":0,"tags":["american","female","english","young","slow","soft"],"user_id":null,"total_ratings":7,"average_rating":4.857142857142857},
  {"id":"37b3f1c8-a01e-4d70-b251-294733f08371","name":"Ryan","description":"Deep African-American male voice. Radio narrator style — engaging and authoritative.","public":true,"ratings":20,"tags":["american","male","english","adult","deep","narrator","engaging","authoritative"],"user_id":null,"total_ratings":15,"average_rating":4.266666666666667},
  {"id":"90295ec4-f0fe-4783-ab33-8b997ddc3ae4","name":"Mason","description":"Adult, serious male. Office-professional tone, guiding and instructive.","public":true,"ratings":13,"tags":["american","male","english","adult","serious","professional","guiding"],"user_id":null,"total_ratings":12,"average_rating":4.25},
  {"id":"e1f2a5a4-18e6-4dd6-8dfb-3c24e99d6a06","name":"Alexa","description":"Very fast-paced, energetic female. Loud and rush-style delivery.","public":true,"ratings":8,"tags":["american","female","english","adult","fast","energetic","loud"],"user_id":"90796703-aa0f-404b-bdff-670d8e4eaa66","total_ratings":153,"average_rating":4.052287581699346},
  {"id":"60fec350-03ff-48fa-9f31-c180f37b1a38","name":"June","description":"Adult female with a fast, nasal voice. Quirky and distinctive delivery.","public":true,"ratings":0,"tags":["american","female","english","adult","fast","nasal"],"user_id":"f230e74a-a3b4-409a-bcda-61253e6af34e","total_ratings":45,"average_rating":4.044444444444444},
  {"id":"13843c96-ab9e-4938-baf3-ad53fcee541d","name":"Nat","description":"Young, resolute and professional female. Flat, no-nonsense delivery.","public":true,"ratings":0,"tags":["american","female","english","young","resolute","professional","flat"],"user_id":"f230e74a-a3b4-409a-bcda-61253e6af34e","total_ratings":61,"average_rating":4.032786885245901},
  {"id":"1d054475-3908-4f64-9158-9d3911fe9597","name":"Adriana","description":"Adult female with a commercial-style voice. Warm but exaggerated delivery.","public":true,"ratings":8,"tags":["american","female","english","adult","warm","commercial"],"user_id":null,"total_ratings":8,"average_rating":3.375},
  {"id":"2f9fdbc7-4bf2-4792-8a18-21ce3c93978f","name":"Maya","description":"Young, serious and professional female. Flat and composed delivery.","public":true,"ratings":54,"tags":["american","female","english","young","serious","professional","flat"],"user_id":null,"total_ratings":29,"average_rating":3.344827586206897},
  {"id":"aec18940-3d5a-4454-acd2-66f685e83b67","name":"Martha","description":"Adult female with slow, narrative delivery. Warm and calming.","public":true,"ratings":0,"tags":["american","female","english","adult","slow","narrative","warm","calm"],"user_id":null,"total_ratings":2,"average_rating":3},

  // ── British English ───────────────────────────────────────────────
  {"id":"9497013c-c348-485b-9ede-9b6e246c9578","name":"Emily","description":"Soft, gentle British female. Whispery mature voice with a soothing tone.","public":true,"ratings":0,"tags":["british","female","english","mature","soft","whispery","gentle"],"user_id":null,"total_ratings":2,"average_rating":5},
  {"id":"013813f0-e96f-4c55-8c2c-b36a6d4d7916","name":"Max","description":"Friendly, happy British male. Professional yet approachable and serious when needed.","public":true,"ratings":0,"tags":["british","male","english","adult","friendly","happy","professional","serious"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"4f5222b2-230f-419b-b776-faa063392584","name":"Trixie","description":"Young, energetic British female. Happy, warm and forward-speaking.","public":true,"ratings":0,"tags":["british","female","english","young","energetic","happy","warm"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"27bd6e08-1d57-4ba8-a290-dcd58bfe78f2","name":"Violette","description":"Mature British female. Serious, polished and emotionally restrained.","public":true,"ratings":0,"tags":["british","female","english","mature","serious","polished","flat"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"f380ad98-4ed6-4b9e-a0fa-37ba0ca9f558","name":"Marnie","description":"Adult, professional British female. Direct and serious delivery.","public":true,"ratings":0,"tags":["british","female","english","adult","professional","direct","serious"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"f97aa643-19b2-4a65-8677-b41839be72bc","name":"Oscar","description":"Adult, cheerful British male. Happy, professional and friendly.","public":true,"ratings":0,"tags":["british","male","english","adult","cheerful","happy","professional","friendly"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"ef8a4528-12f1-41d3-b9d9-c6a4a6d4a6df","name":"Henry","description":"Mature, serious and professional female voice. Commanding presence.","public":true,"ratings":0,"tags":["british","female","english","mature","serious","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"035117be-dfb1-4f46-92d3-59255ac4d96b","name":"Heather","description":"Young, serious British female. Professional and fast-paced.","public":true,"ratings":0,"tags":["british","female","english","young","serious","professional","fast"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"1c2e3ee2-9f5e-43e6-b128-a34b0af46b27","name":"Lucas","description":"Happy, motivated British male. Adult, professional and charismatic.","public":true,"ratings":0,"tags":["british","male","english","adult","happy","motivated","professional","charismatic"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"8aca12e4-a938-413a-88eb-c756ae91655a","name":"Sophie","description":"Calm, soft-spoken British female. Professional and composed.","public":true,"ratings":0,"tags":["british","female","english","adult","calm","soft","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"d512400e-a3eb-4c01-9dfb-620be159cf91","name":"Casey","description":"Adult, happy British female. Motivated, cheerful and professional.","public":true,"ratings":0,"tags":["british","female","english","adult","happy","motivated","cheerful","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"3f222e4d-2624-4bf7-849f-9841ce872015","name":"Clara","description":"Young, happy British female. Motivated and professional.","public":true,"ratings":0,"tags":["british","female","english","young","happy","motivated","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"bc97a31e-b0b8-49e5-bcb8-393fcc6a86ea","name":"Willow","description":"Adult British female with a deep, charismatic voice. Professional and elegant.","public":true,"ratings":0,"tags":["british","female","english","adult","deep","charismatic","professional","elegant"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"26b40c81-22af-4ff3-9821-2c8c6fd38c4d","name":"Ethan","description":"Adult British male with a deep, slow voice. Warm narrator-style delivery.","public":true,"ratings":0,"tags":["british","male","english","adult","deep","slow","narrator","warm"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"31477d18-71c7-4ee0-b41f-d0714689536d","name":"Destiny","description":"Adult, serious British female. Fast-paced delivery.","public":true,"ratings":0,"tags":["british","female","english","adult","serious","fast"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"7b05d026-0d58-4d09-9887-dc45b4b12dcb","name":"Alyssa","description":"Adult, professional British female. Serious and clean delivery.","public":true,"ratings":0,"tags":["british","female","english","adult","professional","serious","clean"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"955a02fb-57e1-418c-865c-d9c7bf9b209a","name":"Brady","description":"Adult British male. Flat, serious and professional tone.","public":true,"ratings":0,"tags":["british","male","english","adult","flat","serious","professional"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"77a066a7-0a91-4aa8-bf62-4745b00ff167","name":"Pryce","description":"Adult British male. Fast-paced, professional and serious.","public":true,"ratings":0,"tags":["british","male","english","adult","fast","professional","serious"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"be3bffbd-c1f1-49a0-8575-58073bfcf9c4","name":"Gabriella","description":"Adult, happy British female. Warm and motivated with a mature tone.","public":true,"ratings":0,"tags":["british","female","english","adult","happy","warm","motivated"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"922d6173-4567-480c-b9a0-bc7c421ad43d","name":"Amelia","description":"Young British female. Commercial-style warmth — relatable and approachable.","public":true,"ratings":0,"tags":["british","female","english","young","warm","relatable","calm"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"dac8fda9-5c55-45e5-b378-ebd311dbb311","name":"Alice","description":"Adult British female. Serious, secretary-style — slow but professional and motherly.","public":true,"ratings":0,"tags":["british","female","english","adult","serious","slow","professional","motherly"],"user_id":null,"total_ratings":6,"average_rating":4.833333333333333},
  {"id":"d70c223b-c039-4f35-9e93-771b2ca481e1","name":"Julia","description":"Adult, warm British female. Motherly, friendly and guiding.","public":true,"ratings":0,"tags":["british","female","english","adult","warm","motherly","friendly","guiding"],"user_id":null,"total_ratings":5,"average_rating":4.6},
  {"id":"a710fd26-0ed7-48e8-86b3-0d4e52d4f500","name":"Rosalie","description":"Young, cheerful British female. Slow-paced, loud and slightly nasal.","public":true,"ratings":0,"tags":["british","female","english","young","cheerful","slow","loud","nasal"],"user_id":null,"total_ratings":4,"average_rating":3.75},
  {"id":"fd9c6765-a2ce-429a-abc7-00be9d1e3a92","name":"Tanner","description":"Adult British male. Cheerful, sympathetic and cooperative. Rustic charm.","public":true,"ratings":1,"tags":["british","male","english","adult","cheerful","sympathetic","cooperative"],"user_id":null,"total_ratings":7,"average_rating":2},

  // ── Australian English ────────────────────────────────────────────
  {"id":"88831b36-7c85-4879-b6b0-22c2ff9f59d7","name":"Lucy","description":"Mature, serious Australian female. Slow, professional narrator-style delivery.","public":true,"ratings":0,"tags":["australian","female","english","mature","serious","slow","professional","narrator"],"user_id":null,"total_ratings":5,"average_rating":5},
  {"id":"63092d46-e154-4e8b-96e9-de85245e82ab","name":"Liam","description":"Young, happy Australian male. Professional, friendly and extroverted.","public":true,"ratings":0,"tags":["australian","male","english","young","happy","professional","friendly","extroverted"],"user_id":null,"total_ratings":0,"average_rating":5},
  {"id":"1c1ca816-f457-4dde-a12a-eaf19fb0b523","name":"Dave","description":"Adult Australian male. Fast, friendly, warm and approachable.","public":true,"ratings":0,"tags":["australian","male","english","adult","fast","friendly","warm","approachable"],"user_id":null,"total_ratings":6,"average_rating":4.5},
  {"id":"8d398d73-a3a6-472b-aad9-ce61b1563a23","name":"Daisy","description":"Young Australian female. Soft, whispery and warm with a gentle pace.","public":true,"ratings":0,"tags":["australian","female","english","young","soft","whispery","warm"],"user_id":null,"total_ratings":4,"average_rating":4.25},
  {"id":"47c02104-7f23-4857-b1a8-e3e939d56642","name":"Ruth","description":"Adult Australian female. Slow, professional and motherly with a strong accent.","public":true,"ratings":0,"tags":["australian","female","english","adult","slow","professional","motherly"],"user_id":null,"total_ratings":5,"average_rating":3.8},

  // ── European Spanish (Spain) ──────────────────────────────────────
  {"id":"ecf0f240-3a2a-4d9e-876a-d175108b2e42","name":"Rosa","description":"Adulta española con voz cálida y natural. Profesional y amigable.","public":true,"ratings":0,"tags":["spanish-european","female","spanish","adult","warm","professional","friendly"],"user_id":null,"total_ratings":2,"average_rating":3.5},

  // ── Latin American Spanish ────────────────────────────────────────
  {"id":"642bfa76-18da-4574-857d-4e1a7144db39","name":"Helena","description":"Joven latina con voz plana y profesional. Acento latinoamericano con seseo.","public":true,"ratings":1,"tags":["spanish-latam","female","spanish","young","flat","professional"],"user_id":null,"total_ratings":7,"average_rating":3.7142857142857144},
  {"id":"6432587a-1454-4b3f-820a-7a2962124b7c","name":"Mariam","description":"Joven latina con voz cálida y alegre. Rápida, enérgica y cercana.","public":true,"ratings":0,"tags":["spanish-latam","female","spanish","young","warm","cheerful","fast","energetic"],"user_id":null,"total_ratings":2,"average_rating":3},
];
